using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MailArchiver.Migrations
{
    /// <inheritdoc />
    public partial class MigrateV2607_3 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Add the ApiKeys table for the read-only REST API. Hand-written
            // idempotent SQL (house style) so the migration is safe to re-run.
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.tables
                        WHERE table_schema = 'mail_archiver' AND table_name = 'ApiKeys'
                    ) THEN
                        CREATE TABLE mail_archiver.""ApiKeys"" (
                            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                            ""UserId"" integer NOT NULL,
                            ""Name"" text NOT NULL,
                            ""KeyPrefix"" character varying(16) NOT NULL,
                            ""KeyHash"" character varying(64) NOT NULL,
                            ""CreatedAt"" timestamp without time zone NOT NULL,
                            ""LastUsedAt"" timestamp without time zone NULL,
                            ""ExpiresAt"" timestamp without time zone NULL,
                            ""RevokedAt"" timestamp without time zone NULL,
                            CONSTRAINT ""PK_ApiKeys"" PRIMARY KEY (""Id""),
                            CONSTRAINT ""FK_ApiKeys_Users_UserId"" FOREIGN KEY (""UserId"")
                                REFERENCES mail_archiver.""Users"" (""Id"") ON DELETE CASCADE
                        );
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE schemaname = 'mail_archiver' AND indexname = 'IX_ApiKeys_KeyHash'
                    ) THEN
                        CREATE UNIQUE INDEX ""IX_ApiKeys_KeyHash"" ON mail_archiver.""ApiKeys"" (""KeyHash"");
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE schemaname = 'mail_archiver' AND indexname = 'IX_ApiKeys_UserId'
                    ) THEN
                        CREATE INDEX ""IX_ApiKeys_UserId"" ON mail_archiver.""ApiKeys"" (""UserId"");
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.tables
                        WHERE table_schema = 'mail_archiver' AND table_name = 'ApiKeys'
                    ) THEN
                        DROP TABLE mail_archiver.""ApiKeys"";
                    END IF;
                END $$;
            ");
        }
    }
}
