// <auto-generated />
using System;
using MailArchiver.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MailArchiver.Migrations
{
    [DbContext(typeof(MailArchiverDbContext))]
    partial class MailArchiverDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("mail_archiver")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MailAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<int?>("DeleteAfterDays")
                        .HasColumnType("integer");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExcludedFolders")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FullSyncIntervalHours")
                        .HasColumnType("integer");

                    b.Property<int?>("ImapPort")
                        .HasColumnType("integer");

                    b.Property<string>("ImapServer")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastFullSync")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LocalRetentionDays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OAuthAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("OAuthRefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OAuthTokenExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .HasMaxLength(10)
                        .HasColumnType("text");

                    b.Property<int?>("SyncIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<bool>("UseSSL")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MailAccounts", "mail_archiver");
                });

            modelBuilder.Entity("MailArchiver.Models.ArchivedEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bcc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BodyUntruncatedHtml")
                        .HasColumnType("text");

                    b.Property<string>("BodyUntruncatedText")
                        .HasColumnType("text");

                    b.Property<string>("Cc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasAttachments")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("HashCreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsOutgoing")
                        .HasColumnType("boolean");

                    b.Property<int>("MailAccountId")
                        .HasColumnType("integer");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawHeaders")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("OriginalBodyHtml")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("OriginalBodyText")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("IX_ArchivedEmails_ContentHash");

                    b.HasIndex("MailAccountId");

                    b.HasIndex("SentDate");

                    b.ToTable("ArchivedEmails", "mail_archiver");
                });

            modelBuilder.Entity("MailArchiver.Models.AccessLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmailId")
                        .HasColumnType("integer");

                    b.Property<string>("EmailFrom")
                        .HasColumnType("text");

                    b.Property<string>("EmailSubject")
                        .HasColumnType("text");

                    b.Property<int?>("MailAccountId")
                        .HasColumnType("integer");

                    b.Property<string>("SearchParameters")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AccessLogs_Timestamp");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_AccessLogs_Type");

                    b.HasIndex("Username")
                        .HasDatabaseName("IX_AccessLogs_Username");

                    b.ToTable("AccessLogs", "mail_archiver");
                });

            modelBuilder.Entity("MailArchiver.Models.EmailAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchivedEmailId")
                        .HasColumnType("integer");

                    b.Property<int?>("AttachmentContentId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("LegacyContent")
                        .HasColumnType("bytea")
                        .HasColumnName("Content");

                    b.Property<string>("ContentId")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedEmailId");

                    b.HasIndex("AttachmentContentId")
                        .HasDatabaseName("IX_EmailAttachments_AttachmentContentId");

                    b.ToTable("EmailAttachments", "mail_archiver");
                });

            modelBuilder.Entity("MailArchiver.Models.AttachmentContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("varchar(64)");


                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("IX_AttachmentContents_Hash");

                    b.ToTable("AttachmentContents", "mail_archiver");
                });


            modelBuilder.Entity("MailArchiver.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelfManager")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastSeenChangelogVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OAuthRemoteUserId")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("TwoFactorBackupCodes")
                        .HasColumnType("text");

                    b.Property<string>("TwoFactorSecret")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OAuthRemoteUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_OAuthRemoteUserId")
                        .HasFilter("\"OAuthRemoteUserId\" IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", "mail_archiver");
                });

            modelBuilder.Entity("MailArchiver.Models.UserMailAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MailAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MailAccountId");

                    b.HasIndex("UserId", "MailAccountId")
                        .IsUnique();

                    b.ToTable("UserMailAccounts", "mail_archiver");
                });

            modelBuilder.Entity("MailArchiver.Models.ArchivedEmail", b =>
                {
                    b.HasOne("MailAccount", "MailAccount")
                        .WithMany("ArchivedEmails")
                        .HasForeignKey("MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailAccount");
                });

            modelBuilder.Entity("MailArchiver.Models.EmailAttachment", b =>
                {
                    b.HasOne("MailArchiver.Models.ArchivedEmail", "ArchivedEmail")
                        .WithMany("Attachments")
                        .HasForeignKey("ArchivedEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MailArchiver.Models.AttachmentContent", "AttachmentContent")
                        .WithMany("Attachments")
                        .HasForeignKey("AttachmentContentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ArchivedEmail");

                    b.Navigation("AttachmentContent");
                });


            modelBuilder.Entity("MailArchiver.Models.UserMailAccount", b =>
                {
                    b.HasOne("MailAccount", "MailAccount")
                        .WithMany("UserMailAccounts")
                        .HasForeignKey("MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MailArchiver.Models.User", "User")
                        .WithMany("UserMailAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MailAccount", b =>
                {
                    b.Navigation("ArchivedEmails");

                    b.Navigation("UserMailAccounts");
                });

            modelBuilder.Entity("MailArchiver.Models.ArchivedEmail", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("MailArchiver.Models.AttachmentContent", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("MailArchiver.Models.User", b =>
                {
                    b.Navigation("UserMailAccounts");
                });


            modelBuilder.Entity("MailArchiver.Models.BandwidthUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("BytesDownloaded")
                        .HasColumnType("bigint");

                    b.Property<long>("BytesUploaded")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmailsProcessed")
                        .HasColumnType("integer");

                    b.Property<bool>("LimitReached")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LimitResetTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MailAccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_BandwidthUsage_Date");

                    b.HasIndex("MailAccountId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_BandwidthUsage_Account_Date");

                    b.ToTable("BandwidthUsage", "mail_archiver");
                });

            modelBuilder.Entity("MailArchiver.Models.SyncCheckpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("BytesDownloaded")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastMessageDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastMessageId")
                        .HasColumnType("text");

                    b.Property<int>("MailAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MailAccountId")
                        .HasDatabaseName("IX_SyncCheckpoints_AccountId");

                    b.HasIndex("MailAccountId", "FolderName")
                        .IsUnique()
                        .HasDatabaseName("IX_SyncCheckpoints_Account_Folder");

                    b.ToTable("SyncCheckpoints", "mail_archiver");
                });

            modelBuilder.Entity("MailArchiver.Models.AccountStorageCache", b =>
                {
                    b.Property<int>("MailAccountId")
                        .HasColumnType("integer");

                    b.Property<long>("AttachmentBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<long>("MailBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<long>("TotalBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MailAccountId");

                    b.ToTable("AccountStorageCache", "mail_archiver");
                });

            modelBuilder.Entity("MailArchiver.Models.AccountStorageBackfillState", b =>
                {
                    b.Property<int>("MailAccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Pending");

                    b.HasKey("MailAccountId");

                    b.ToTable("AccountStorageBackfillState", "mail_archiver");
                });

            modelBuilder.Entity("MailArchiver.Models.BandwidthUsage", b =>
                {
                    b.HasOne("MailArchiver.Models.MailAccount", "MailAccount")
                        .WithMany()
                        .HasForeignKey("MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailAccount");
                });

            modelBuilder.Entity("MailArchiver.Models.SyncCheckpoint", b =>
                {
                    b.HasOne("MailArchiver.Models.MailAccount", "MailAccount")
                        .WithMany()
                        .HasForeignKey("MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailAccount");
                });

            modelBuilder.Entity("MailArchiver.Models.AccountStorageCache", b =>
                {
                    b.HasOne("MailAccount", "MailAccount")
                        .WithOne()
                        .HasForeignKey("MailArchiver.Models.AccountStorageCache", "MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailAccount");
                });

            modelBuilder.Entity("MailArchiver.Models.AccountStorageBackfillState", b =>
                {
                    b.HasOne("MailAccount", "MailAccount")
                        .WithOne()
                        .HasForeignKey("MailArchiver.Models.AccountStorageBackfillState", "MailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
